name: Deploy production backend

concurrency: production

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: clone repo
        uses: actions/checkout@v3

      - uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
        with:
          ORIGIN: 92.255.109.65
          SSHKEY: ${{ secrets.SSH_PRIVATE_KEY }}
          NAME: production
          USER: root

      - name: run docker compose
        run: |
          echo $PRODUCTION_ENV | base64 -d > .env.production
          docker context create --docker host=ssh://production production
          docker context use production
          docker compose --env-file=.env.production up --build -d
        env:
          PRODUCTION_ENV: ${{ secrets.PRODUCTION_ENV }}
