name: Deploy production backend

concurrency: production

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: clone repo
        uses: actions/checkout@v3
        
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 92.255.109.65
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            eval "$(ssh-agent -s)"
            ssh-add /root/gh_keys/id_rsa
            rm -rf traning-agents-nest-api
            git clone git@github.com:Roman-Shubnikov/traning-agents-nest-api.git
            cd traning-agents-nest-api
            echo ${{ secrets.PRODUCTION_ENV }} | base64 -d > .env
            docker compose up --build -d
            cd ..
            rm -rf traning-agents-nest-api
